services:
  - type: private_service
    name: lavalink-v2
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: DEFAULT_GUILD_ID
        sync: false
      - key: AUTO_JOIN_VOICE_CHANNEL_ID
        sync: false
      - key: VOICE_TEXT_CHANNEL_ID
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: EMBED_COLOR
        value: "0x2B2D31"
      - key: LAVALINK_HOST
        value: "lavalink-private"
      - key: LAVALINK_PORT
        value: "2333"
      - key: LAVALINK_PASSWORD
        value: "youshallnotpass"
      - key: LAVALINK_SECURE
        value: "false"
      - key: DEFAULT_VOLUME
        value: "70"
      - key: MAX_QUEUE_LENGTH
        value: "200"
      - key: SEARCH_LIMIT
        value: "5"

  - type: private_service
    name: lavalink-private
    runtime: docker
    dockerContext: ./lavalink
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: "2333"
      - key: LAVALINK_SERVER_PASSWORD
        value: "youshallnotpass"